### ISSUE TITLE
Pycharm 2016

### ISSUE THREAD

**Issue by ibnbay** [chlab/pycharm-django-live-templates#1]
There is no folder /Users/[user name]/Library/Preferences/PyCharm2016.1/templates

What should i do?

**Comment by ibnbay** [comment]
just found this
https://github.com/brmc/pycharm-djaneiro
It's simple installation and very complete tags...

**Comment by sethlivingston** [comment]
The folder is

`~/.PyCharm[VERSION]/config/templates`

djaneiro is nice but does far more than I need; pycharm-django-live-templates is perfect.
